/*
** Generated by WorkShop Visual
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/CascadeB.h>
#include <Xm/DialogS.h>
#include <Xm/FileSB.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/List.h>
#include <Xm/PanedW.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/ScrollBar.h>
#include <Xm/ScrolledW.h>
#include <Xm/SelectioB.h>
#include <Xm/Separator.h>
#include <Xm/Text.h>
#include <Xm/TextF.h>
#include <Xm/LabelG.h>
#include <Xm/PushBG.h>
#include <Xm/SeparatoG.h>
#include <Xm/ToggleBG.h>

#ifdef USE_XPM
# include <X11/xpm.h>
# include "dm2k_faceplate.xpm"
#endif

#include "faceplateGUI.h"

extern void cbFaceplateDlg(Widget, XtPointer, XtPointer) ;
extern void cbFile(Widget, XtPointer, XtPointer) ;
extern void cbGroupAttributes(Widget, XtPointer, XtPointer) ;
extern void cbFaceplateCoordinates(Widget, XtPointer, XtPointer) ;
extern void cbWholeGroup(Widget, XtPointer, XtPointer) ;
extern void cbFaceplateCell(Widget, XtPointer, XtPointer) ;
extern void cbFaceplateAdlFile(Widget, XtPointer, XtPointer) ;
extern void cbFaceplateSubmit(Widget, XtPointer, XtPointer) ;
extern void cbAdlFileSelect(Widget, XtPointer, XtPointer) ;
extern void cbFaceplateFileSelect(Widget, XtPointer, XtPointer) ;

void XDmanage_link ( Widget w, XtPointer client_data, XtPointer call_data )
{
  if ( client_data && *(Widget *)client_data )
    XtManageChild ( *(Widget *)client_data );
}

void XDunmanage_link ( Widget w, XtPointer client_data, XtPointer call_data )
{
  if ( client_data && *(Widget *)client_data )
    XtUnmanageChild ( *(Widget *)client_data );
}

void XDpopup_link ( Widget w, XtPointer client_data, XtPointer call_data )
{
  if ( client_data && *(Widget *)client_data )
    XtPopup ( *(Widget *)client_data, XtGrabNone );
}

void XDpopdown_link ( Widget w, XtPointer client_data, XtPointer call_data )
{
  if ( client_data && *(Widget *)client_data )
    XtPopdown ( *(Widget *)client_data );
}

void XDmap_link ( Widget w, XtPointer client_data, XtPointer call_data )
{
  if ( client_data && *(Widget *)client_data )
    XtMapWidget (*(Widget *)client_data);
}

void XDunmap_link ( Widget w, XtPointer client_data, XtPointer call_data )
{
  if ( client_data && *(Widget *)client_data )
    XtUnmapWidget (*(Widget *)client_data);
}

void XDenable_link ( Widget w, XtPointer client_data, XtPointer call_data )
{
  if ( client_data && *(Widget *)client_data )
    XtSetSensitive (*(Widget *)client_data, TRUE);
}

void XDdisable_link ( Widget w, XtPointer client_data, XtPointer call_data )
{
  if ( client_data && *(Widget *)client_data )
    XtSetSensitive (*(Widget *)client_data, FALSE);
}


FaceplateGUI * getFaceplateGUI(Widget w)
{
  FaceplateGUI * fGUI = NULL;
  WidgetList     wList;
  int            n;
  int            i;

  if (w == (Widget)NULL)
    return NULL;

  while (w && !XtIsSubclass(w, topLevelShellWidgetClass)) {
    w = XtParent(w);
  }

  if (w == (Widget)NULL)
    return NULL;

  XtVaGetValues(w, 
		XtNchildren, &wList,
		XtNnumChildren, &n,
		NULL);

  for (i = 0; i < n; i++)
    if (strcmp(XtName(wList[i]), LINK_WIDGET_NAME) == 0) {
      XtVaGetValues(wList[i], XmNuserData, &fGUI, NULL);
      break;
    }
  
  return fGUI;
}

void setFaceplateSensitivity(FaceplateGUI * fGUI)
{
  if (fGUI == NULL)
    return;

  if (fGUI->fpg != NULL) {
    XtSetSensitive(fGUI->wComments, True);
    XtSetSensitive(fGUI->wTitle, True);
    XtSetSensitive(fGUI->wNotes, True);
    XtSetSensitive(fGUI->wX, True);
    XtSetSensitive(fGUI->wY, True);
    XtSetSensitive(fGUI->wHeight, True);
    XtSetSensitive(fGUI->wWidth, True);
    XtSetSensitive(fGUI->wInPixelTGL, True);
    XtSetSensitive(fGUI->wFractionBaseTGL, True);
    XtSetSensitive(fGUI->wFractionBaseTXT, False);
    XtSetSensitive(fGUI->wCell00, True);
    XtSetSensitive(fGUI->wCell10, True);
    XtSetSensitive(fGUI->wCell20, True);
    XtSetSensitive(fGUI->wCell30, True);
    XtSetSensitive(fGUI->wCell40, True);
    XtSetSensitive(fGUI->wCell50, True);
    XtSetSensitive(fGUI->wCell60, True);
    XtSetSensitive(fGUI->wCell70, True);
    XtSetSensitive(fGUI->wCell01, True);
    XtSetSensitive(fGUI->wCell11, True);
    XtSetSensitive(fGUI->wCell21, True);
    XtSetSensitive(fGUI->wCell31, True);
    XtSetSensitive(fGUI->wCell41, True);
    XtSetSensitive(fGUI->wCell51, True);
    XtSetSensitive(fGUI->wCell61, True);
    XtSetSensitive(fGUI->wCell71, True);
    XtSetSensitive(fGUI->wFaceplateX, True);
    XtSetSensitive(fGUI->wFaceplateY, True);
    XtSetSensitive(fGUI->wFaceplateHeigth, True);
    XtSetSensitive(fGUI->wFaceplateWidth, True);
    XtSetSensitive(fGUI->wSelectedAdlFile, True);
    XtSetSensitive(fGUI->wFaceplateAdlFileBrowse, True);
    XtSetSensitive(fGUI->wFaceplateReset, True);
    XtSetSensitive(fGUI->wAddNewFaceplate, True);
    XtSetSensitive(fGUI->wApplayChanges, True);
    XtSetSensitive(fGUI->wDeleteFaceplate, True);
  } else {
    XtSetSensitive(fGUI->wComments, False);
    XtSetSensitive(fGUI->wTitle, False);
    XtSetSensitive(fGUI->wNotes, False);
    XtSetSensitive(fGUI->wX, False);
    XtSetSensitive(fGUI->wY, False);
    XtSetSensitive(fGUI->wHeight, False);
    XtSetSensitive(fGUI->wWidth, False);
    XtSetSensitive(fGUI->wInPixelTGL, False);
    XtSetSensitive(fGUI->wFractionBaseTGL, False);
    XtSetSensitive(fGUI->wFractionBaseTXT, False);
    XtSetSensitive(fGUI->wCell00, False);
    XtSetSensitive(fGUI->wCell10, False);
    XtSetSensitive(fGUI->wCell20, False);
    XtSetSensitive(fGUI->wCell30, False);
    XtSetSensitive(fGUI->wCell40, False);
    XtSetSensitive(fGUI->wCell50, False);
    XtSetSensitive(fGUI->wCell60, False);
    XtSetSensitive(fGUI->wCell70, False);
    XtSetSensitive(fGUI->wCell01, False);
    XtSetSensitive(fGUI->wCell11, False);
    XtSetSensitive(fGUI->wCell21, False);
    XtSetSensitive(fGUI->wCell31, False);
    XtSetSensitive(fGUI->wCell41, False);
    XtSetSensitive(fGUI->wCell51, False);
    XtSetSensitive(fGUI->wCell61, False);
    XtSetSensitive(fGUI->wCell71, False);
    XtSetSensitive(fGUI->wFaceplateX, False);
    XtSetSensitive(fGUI->wFaceplateY, False);
    XtSetSensitive(fGUI->wFaceplateHeigth, False);
    XtSetSensitive(fGUI->wFaceplateWidth, False);
    XtSetSensitive(fGUI->wSelectedAdlFile, False);
    XtSetSensitive(fGUI->wFaceplateAdlFileBrowse, False);
    XtSetSensitive(fGUI->wFaceplateReset, False);
    XtSetSensitive(fGUI->wAddNewFaceplate, False);
    XtSetSensitive(fGUI->wApplayChanges, False);
    XtSetSensitive(fGUI->wDeleteFaceplate, False);
  }
}


void create_shell5 (Widget parent)
{
  Widget children[16];      /* Children to manage */
  Display *display = XtDisplay ( parent );
  Arg al[64];                    /* Arg List */
  register int ac = 0;           /* Arg Count */
  XrmValue from_value, to_value; /* For resource conversion */
  XmString xmstrings[16];    /* temporary storage for XmStrings */
  Widget menuBar3 = (Widget)NULL;
  Widget cascade13 = (Widget)NULL;
  Widget menu3 = (Widget)NULL;
  Widget separator14 = (Widget)NULL;
  Widget separator15 = (Widget)NULL;
  Widget panedWindow1 = (Widget)NULL;
  Widget frame15 = (Widget)NULL;
  Widget form41 = (Widget)NULL;
  Widget label84 = (Widget)NULL;
  Widget scrolledText4 = (Widget)NULL;
  Widget label85 = (Widget)NULL;
  Widget label86 = (Widget)NULL;
  Widget form42 = (Widget)NULL;
  Widget separator1 = (Widget)NULL;
  Widget form43 = (Widget)NULL;
  Widget label87 = (Widget)NULL;
  Widget label88 = (Widget)NULL;
  Widget label89 = (Widget)NULL;
  Widget label90 = (Widget)NULL;
  Widget label91 = (Widget)NULL;
  Widget radioBox3 = (Widget)NULL;
  Widget label2 = (Widget)NULL;
  Widget label92 = (Widget)NULL;
  Widget frame16 = (Widget)NULL;
  Widget form44 = (Widget)NULL;
  Widget scrolledWin8 = (Widget)NULL;
  Widget scrollbar31 = (Widget)NULL;
  Widget scrollbar32 = (Widget)NULL;
  Widget label93 = (Widget)NULL;
  Widget frame17 = (Widget)NULL;
  Widget label94 = (Widget)NULL;
  Widget form46 = (Widget)NULL;
  Widget label95 = (Widget)NULL;
  Widget rowcol14 = (Widget)NULL;
  Widget rowcol15 = (Widget)NULL;
  Widget rowcol16 = (Widget)NULL;
  Widget form47 = (Widget)NULL;
  Widget label97 = (Widget)NULL;
  Widget label98 = (Widget)NULL;
  Widget label99 = (Widget)NULL;
  Widget label100 = (Widget)NULL;
  Widget form48 = (Widget)NULL;
  Widget label101 = (Widget)NULL;
  Widget label102 = (Widget)NULL;
  Widget frame18 = (Widget)NULL;
  Widget form49 = (Widget)NULL;
  Widget scrolledWin9 = (Widget)NULL;
  Widget scrollbar33 = (Widget)NULL;
  Widget scrollbar34 = (Widget)NULL;
  Widget label103 = (Widget)NULL;
  Widget label105 = (Widget)NULL;
  Widget separator19 = (Widget)NULL;
  Widget separator20 = (Widget)NULL;
  Widget separator21 = (Widget)NULL;
  Widget form51 = (Widget)NULL;
  FaceplateGUI * fGUI;

  static Pixmap pixmap = None;
#ifdef USE_XPM
  XpmAttributes xpmAttr;


  if (pixmap == None) {
    xpmAttr.valuemask = XpmColormap;
    xpmAttr.colormap = cmap;
    (void)XpmCreatePixmapFromData (display, 
				   XDefaultRootWindow(display),
				   dm2k_faceplate_xpm,
				   &pixmap, 
				   NULL, 
				   &xpmAttr);
  }
#endif


  fGUI = (FaceplateGUI*) calloc (1, sizeof(FaceplateGUI));
  if (fGUI == NULL)
    return;
  
  memset ((char*)fGUI, 0, sizeof(FaceplateGUI));

  ac = 0;

  if (pixmap != None) {
    XtSetArg(al[ac], XtNiconPixmap, pixmap); ac++;
  }

  XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
  XtSetArg(al[ac], XmNtitle, "newFaceplate.mfp"); ac++;
  fGUI->wFaceplateDlgShell = XtCreatePopupShell ( "wFaceplateDlgShell", topLevelShellWidgetClass, parent, al, ac ); 

  ac = 0;
  XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
  XtSetArg(al[ac], XmNuserData, (XtPointer)fGUI); ac++;
  fGUI->wFaceplateDlg = XmCreateForm ( fGUI->wFaceplateDlgShell, "wFaceplateDlg", al, ac );
  XtAddCallback(fGUI->wFaceplateDlg, XtNdestroyCallback, cbFaceplateDlg,
		NULL);
  ac = 0;
  menuBar3 = XmCreateMenuBar ( fGUI->wFaceplateDlg, "menuBar3", al, ac );
  XtSetArg(al[ac], XmNx, 5); ac++;
  XtSetArg(al[ac], XmNy, 5); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "File ", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  from_value.addr = "F";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menuBar3, XmRString, &from_value, XmRKeySym, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
    }
  cascade13 = XmCreateCascadeButton ( menuBar3, "cascade13", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  menu3 = XmCreatePulldownMenu ( menuBar3, "menu3", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "New ", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  from_value.addr = "-*-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRFontList, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
    }
  from_value.addr = "N";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRKeySym, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
    }
  fGUI->wFileNew = XmCreateCascadeButton ( menu3, "wFileNew", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "Open ", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  from_value.addr = "-*-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRFontList, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
    }
  from_value.addr = "O";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRKeySym, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
    }
  fGUI->wFileOpen = XmCreateCascadeButton ( menu3, "wFileOpen", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  separator14 = XmCreateSeparator ( menu3, "separator14", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "Save ", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  from_value.addr = "-*-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRFontList, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
    }
  from_value.addr = "S";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRKeySym, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
    }
  fGUI->wFileSave = XmCreateCascadeButton ( menu3, "wFileSave", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "Save As ...", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  from_value.addr = "-*-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRFontList, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
    }
  from_value.addr = "A";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRKeySym, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
    }
  fGUI->wFileSaveAs = XmCreateCascadeButton ( menu3, "wFileSaveAs", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  separator15 = XmCreateSeparator ( menu3, "separator15", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "Close", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  from_value.addr = "-*-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRFontList, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
    }
  from_value.addr = "C";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (menu3, XmRString, &from_value, XmRKeySym, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
    }
  fGUI->wFileClose = XmCreateCascadeButton ( menu3, "wFileClose", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  panedWindow1 = XmCreatePanedWindow ( fGUI->wFaceplateDlg, "panedWindow1", al, ac );
  frame15 = XmCreateFrame ( panedWindow1, "frame15", al, ac );
  form41 = XmCreateForm ( frame15, "form41", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "Title:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetArg(al[ac], XmNalignment, XmALIGNMENT_END); ac++;
  label84 = XmCreateLabel ( form41, "label84", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNeditMode, XmMULTI_LINE_EDIT); ac++;
  fGUI->wComments = XmCreateScrolledText ( form41, "wComments", al, ac );
  ac = 0;
  scrolledText4 = XtParent ( fGUI->wComments );

  XtSetArg(al[ac], XmNheight, 64); ac++;
  XtSetValues ( scrolledText4,al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "Comments:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetArg(al[ac], XmNalignment, XmALIGNMENT_END); ac++;
  label85 = XmCreateLabel ( form41, "label85", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  fGUI->wTitle = XmCreateTextField ( form41, "wTitle", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "Notes:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetArg(al[ac], XmNalignment, XmALIGNMENT_END); ac++;
  label86 = XmCreateLabel ( form41, "label86", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  fGUI->wNotes = XmCreateTextField ( form41, "wNotes", al, ac );
  form42 = XmCreateForm ( form41, "form42", al, ac );
  separator1 = XmCreateSeparator ( form42, "separator1", al, ac );
  form43 = XmCreateForm ( form41, "form43", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "x:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label87 = XmCreateLabel ( form43, "label87", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNcolumns, 5); ac++;
  fGUI->wX = XmCreateTextField ( form43, "wX", al, ac );
  ac = 0;
  XtSetArg(al[ac], XmNcolumns, 5); ac++;
  fGUI->wY = XmCreateTextField ( form43, "wY", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "width:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label88 = XmCreateLabel ( form43, "label88", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNcolumns, 5); ac++;
  fGUI->wHeight = XmCreateTextField ( form43, "wHeight", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "height:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label89 = XmCreateLabel ( form43, "label89", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNcolumns, 5); ac++;
  fGUI->wWidth = XmCreateTextField ( form43, "wWidth", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "y:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label90 = XmCreateLabel ( form43, "label90", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "Location:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetArg(al[ac], XmNalignment, XmALIGNMENT_END); ac++;
  label91 = XmCreateLabel ( form41, "label91", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
  radioBox3 = XmCreateRadioBox ( form41, "radioBox3", al, ac );
  ac = 0;
  XtSetArg(al[ac], XmNx, 3); ac++;
  XtSetArg(al[ac], XmNy, 3); ac++;
  XtSetArg(al[ac], XmNshadowThickness, 0); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "in pixel", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  from_value.addr = "-adobe-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (radioBox3, XmRString, &from_value, XmRFontList, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
    }
  XtSetArg(al[ac], XmNset, TRUE); ac++;
  fGUI->wInPixelTGL = XmCreateToggleButtonGadget ( radioBox3, "wInPixelTGL", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNx, 105); ac++;
  XtSetArg(al[ac], XmNy, 3); ac++;
  XtSetArg(al[ac], XmNshadowThickness, 0); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "fraction base", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  from_value.addr = "-adobe-helvetica-medium-r-normal--12-120-75-75-p-67-iso8859-1";
  from_value.size = strlen( from_value.addr ) + 1;
  to_value.addr = NULL;
  XtConvertAndStore (radioBox3, XmRString, &from_value, XmRFontList, &to_value);
  if ( to_value.addr )
    {
      XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
    }
  fGUI->wFractionBaseTGL = XmCreateToggleButtonGadget ( radioBox3, "wFractionBaseTGL", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "Faceplate\ncoordinates", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetArg(al[ac], XmNalignment, XmALIGNMENT_END); ac++;
  label2 = XmCreateLabel ( form41, "label2", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNsensitive, FALSE); ac++;
  XtSetArg(al[ac], XmNcolumns, 3); ac++;
  fGUI->wFractionBaseTXT = XmCreateTextField ( form41, "wFractionBaseTXT", al, ac );
  ac = 0;
  XtSetArg(al[ac], XmNchildType, XmFRAME_TITLE_CHILD); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "Group attributes", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label92 = XmCreateLabel ( frame15, "label92", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNmarginHeight, 4); ac++;
  XtSetArg(al[ac], XmNmarginWidth, 4); ac++;
  frame16 = XmCreateFrame ( panedWindow1, "frame16", al, ac );
  ac = 0;
  form44 = XmCreateForm ( frame16, "form44", al, ac );
  XtSetArg(al[ac], XmNscrollingPolicy, XmAUTOMATIC); ac++;
  scrolledWin8 = XmCreateScrolledWindow ( form44, "scrolledWin8", al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNhorizontalScrollBar, &scrollbar31 ); ac++;
  XtSetArg(al[ac], XmNverticalScrollBar, &scrollbar32 ); ac++;
  XtGetValues(scrolledWin8, al, ac );
  ac = 0;
  fGUI->wGroupForm = XmCreateForm ( scrolledWin8, "wGroupForm", al, ac );
  XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
  XtSetArg(al[ac], XmNpacking, XmPACK_TIGHT); ac++;
  XtSetArg(al[ac], XmNnumColumns, 8); ac++; 
  fGUI->wGroupRowColumn = XmCreateRadioBox ( fGUI->wGroupForm, "wGroupRowColumn", al, ac );
  ac = 0;
  XtSetArg(al[ac], XmNchildType, XmFRAME_TITLE_CHILD); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "Whole group", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label93 = XmCreateLabel ( frame16, "label93", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  frame17 = XmCreateFrame ( panedWindow1, "frame17", al, ac );
  XtSetArg(al[ac], XmNchildType, XmFRAME_TITLE_CHILD); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "Faceplate", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label94 = XmCreateLabel ( frame17, "label94", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNfractionBase, 10); ac++;
  form46 = XmCreateForm ( frame17, "form46", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "Select location as a cell from the grid..", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetArg(al[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
  label95 = XmCreateLabel ( form46, "label95", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNspacing, 0); ac++;
  XtSetArg(al[ac], XmNmarginWidth, 1); ac++;
  XtSetArg(al[ac], XmNmarginHeight, 2); ac++;
  XtSetArg(al[ac], XmNorientation, XmVERTICAL); ac++;
  rowcol14 = XmCreateRowColumn ( form46, "rowcol14", al, ac );
  ac = 0;
  XtSetArg(al[ac], XmNspacing, 0); ac++;
  XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
  XtSetArg(al[ac], XmNmarginHeight, 0); ac++;
  XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
  XtSetArg(al[ac], XmNpacking, XmPACK_TIGHT); ac++;
  rowcol15 = XmCreateRowColumn ( rowcol14, "rowcol15", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "0,0", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell00 = XmCreatePushButton ( rowcol15, "wCell00", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNx, 30); ac++;
  XtSetArg(al[ac], XmNy, 0); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "1,0", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell10 = XmCreatePushButton ( rowcol15, "wCell10", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "2,0", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell20 = XmCreatePushButton ( rowcol15, "wCell20", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "3,0", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell30 = XmCreatePushButton ( rowcol15, "wCell30", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "4,0", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell40 = XmCreatePushButton ( rowcol15, "wCell40", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "5,0", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell50 = XmCreatePushButton ( rowcol15, "wCell50", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "6,0", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell60 = XmCreatePushButton ( rowcol15, "wCell60", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNwidth, 63); ac++;
  XtSetArg(al[ac], XmNheight, 25); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "7,0", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell70 = XmCreatePushButton ( rowcol15, "wCell70", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNx, 1); ac++;
  XtSetArg(al[ac], XmNy, 28); ac++;
  XtSetArg(al[ac], XmNwidth, 267); ac++;
  XtSetArg(al[ac], XmNheight, 34); ac++;
  XtSetArg(al[ac], XmNspacing, 0); ac++;
  XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
  XtSetArg(al[ac], XmNmarginHeight, 0); ac++;
  XtSetArg(al[ac], XmNorientation, XmHORIZONTAL); ac++;
  rowcol16 = XmCreateRowColumn ( rowcol14, "rowcol16", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "0,1", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell01 = XmCreatePushButton ( rowcol16, "wCell01", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNx, 30); ac++;
  XtSetArg(al[ac], XmNy, 0); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "1,1", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell11 = XmCreatePushButton ( rowcol16, "wCell11", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "2,1", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell21 = XmCreatePushButton ( rowcol16, "wCell21", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "3,1", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell31 = XmCreatePushButton ( rowcol16, "wCell31", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "4,1", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell41 = XmCreatePushButton ( rowcol16, "wCell41", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "5,1", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell51 = XmCreatePushButton ( rowcol16, "wCell51", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "6,1", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell61 = XmCreatePushButton ( rowcol16, "wCell61", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNwidth, 39); ac++;
  XtSetArg(al[ac], XmNheight, 27); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "7,1", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wCell71 = XmCreatePushButton ( rowcol16, "wCell71", al, ac );

  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  form47 = XmCreateForm ( form46, "form47", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "x:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label97 = XmCreateLabel ( form47, "label97", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNcolumns, 5); ac++;
  fGUI->wFaceplateX = XmCreateTextField ( form47, "wFaceplateX", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "y:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label98 = XmCreateLabel ( form47, "label98", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNcolumns, 5); ac++;
  fGUI->wFaceplateY = XmCreateTextField ( form47, "wFaceplateY", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "width:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label99 = XmCreateLabel ( form47, "label99", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNcolumns, 5); ac++;
  fGUI->wFaceplateHeigth = XmCreateTextField ( form47, "wFaceplateHeigth", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "height:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label100 = XmCreateLabel ( form47, "label100", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNcolumns, 5); ac++;
  fGUI->wFaceplateWidth = XmCreateTextField ( form47, "wFaceplateWidth", al, ac );
  ac = 0;
  form48 = XmCreateForm ( form46, "form48", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "adl file:", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetArg(al[ac], XmNalignment, XmALIGNMENT_END); ac++;
  label101 = XmCreateLabel ( form48, "label101", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  fGUI->wSelectedAdlFile = XmCreateTextField ( form48, "selectAdlFileText", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "browse..", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wFaceplateAdlFileBrowse = XmCreatePushButton ( form48, "wFaceplateAdlFileBrowse", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "..or type in the position and  the size.", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetArg(al[ac], XmNalignment, XmALIGNMENT_BEGINNING); ac++;
  label102 = XmCreateLabel ( form46, "label102", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  frame18 = XmCreateFrame ( form46, "frame18", al, ac );
  form49 = XmCreateForm ( frame18, "form49", al, ac );
  XtSetArg(al[ac], XmNspacing, 0); ac++;
  XtSetArg(al[ac], XmNscrollingPolicy, XmAUTOMATIC); ac++;
  scrolledWin9 = XmCreateScrolledWindow ( form49, "scrolledWin9", al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNhorizontalScrollBar, &scrollbar33 ); ac++;
  XtSetArg(al[ac], XmNverticalScrollBar, &scrollbar34 ); ac++;
  XtGetValues(scrolledWin9, al, ac );
  ac = 0;
  XtSetArg(al[ac], XmNmarginWidth, 1); ac++;
  XtSetArg(al[ac], XmNmarginHeight, 1); ac++;
  fGUI->wFaceplateMacroRowColomn = XmCreateRowColumn ( scrolledWin9, "wFaceplateMacroRowColomn", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "name / value", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label103 = XmCreateLabel ( form49, "label103", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNchildType, XmFRAME_TITLE_CHILD); ac++;
  xmstrings[0] = XmStringCreateLtoR ( "macro substitutions", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  label105 = XmCreateLabel ( frame18, "label105", al, ac );

  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  separator19 = XmCreateSeparator ( form46, "separator19", al, ac );
  separator20 = XmCreateSeparator ( form46, "separator20", al, ac );
  separator21 = XmCreateSeparator ( form46, "separator21", al, ac );
  xmstrings[0] = XmStringCreateLtoR ( "add new faceplate", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wAddNewFaceplate = XmCreatePushButton ( form46, "wAddNewFaceplate", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "apply changes", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wApplayChanges = XmCreatePushButton ( form46, "wApplayChanges", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  xmstrings[0] = XmStringCreateLtoR ( "delete faceplate", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wDeleteFaceplate = XmCreatePushButton ( form46, "wDeleteFaceplate", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XtSetArg(al[ac], XmNheight, 8); ac++;
  form51 = XmCreateForm ( form46, "form51", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "unselect cell", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  fGUI->wFaceplateReset = XmCreatePushButton ( form46, "wFaceplateReset", al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, -33); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetValues ( menuBar3,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNtopWidget, menuBar3); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 0); ac++;
  XtSetValues ( panedWindow1,al, ac );
  ac = 0;
  XtAddCallback( fGUI->wFileNew, XmNactivateCallback, cbFile, (XtPointer) FP_FILE_NEW );
  XtAddCallback( fGUI->wFileOpen, XmNactivateCallback, cbFile, (XtPointer) FP_FILE_OPEN );
  XtAddCallback( fGUI->wFileSave, XmNactivateCallback, cbFile, (XtPointer) FP_FILE_SAVE );
  XtAddCallback( fGUI->wFileSaveAs, XmNactivateCallback, cbFile, (XtPointer) FP_FILE_SAVEAS );
  XtAddCallback( fGUI->wFileClose, XmNactivateCallback, cbFile, (XtPointer) FP_FILE_CLOSE );
  children[ac++] = fGUI->wFileNew;
  children[ac++] = fGUI->wFileOpen;
  children[ac++] = separator14;
  children[ac++] = fGUI->wFileSave;
  children[ac++] = fGUI->wFileSaveAs;
  children[ac++] = separator15;
  children[ac++] = fGUI->wFileClose;
  XtManageChildren(children, ac);
  ac = 0;
  XtSetArg(al[ac], XmNsubMenuId, menu3); ac++;
  XtSetValues ( cascade13, al, ac );
  ac = 0;
  children[ac++] = cascade13;
  XtManageChildren(children, ac);
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, fGUI->wTitle); ac++;
  XtSetValues ( label84,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 4); ac++;
  XtSetArg(al[ac], XmNtopWidget, fGUI->wNotes); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomWidget, form42); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 12); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 4); ac++;
  XtSetValues ( scrolledText4,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopWidget, scrolledText4); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, scrolledText4); ac++;
  XtSetValues ( label85,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 12); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 4); ac++;
  XtSetValues ( fGUI->wTitle,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 37); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, fGUI->wNotes); ac++;
  XtSetValues ( label86,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 4); ac++;
  XtSetArg(al[ac], XmNtopWidget, fGUI->wTitle); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 12); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 4); ac++;
  XtSetValues ( fGUI->wNotes,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomWidget, form43); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 2); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 2); ac++;
  XtSetValues ( form42,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomWidget, fGUI->wFractionBaseTXT); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 12); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( form43,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopWidget, form43); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomWidget, form43); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, form43); ac++;
  XtSetValues ( label91,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 12); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( radioBox3,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNtopWidget, radioBox3); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomWidget, radioBox3); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightOffset, 0); ac++;
  XtSetArg(al[ac], XmNrightWidget, radioBox3); ac++;
  XtSetValues ( label2,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNleftWidget, radioBox3); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( fGUI->wFractionBaseTXT,al, ac );
  ac = 0;
  XtAddCallback( fGUI->wComments, XmNvalueChangedCallback, cbGroupAttributes, (XtPointer) FP_GROUP_ATTR_COMMENTS );
  XtManageChild(fGUI->wComments);
  XtAddCallback( fGUI->wTitle, XmNvalueChangedCallback, cbGroupAttributes, (XtPointer) FP_GROUP_ATTR_TITLE );
  XtAddCallback( fGUI->wNotes, XmNvalueChangedCallback, cbGroupAttributes, (XtPointer) FP_GROUP_ATTR_NOTES );

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 2); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 2); ac++;
  XtSetValues ( separator1,al, ac );
  ac = 0;
  children[ac++] = separator1;
  XtManageChildren(children, ac);
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 8); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( label87,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label87); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( fGUI->wX,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label90); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( fGUI->wY,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 24); ac++;
  XtSetArg(al[ac], XmNleftWidget, fGUI->wY); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( label88,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, -1); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label89); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 0); ac++;
  XtSetValues ( fGUI->wHeight,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 8); ac++;
  XtSetArg(al[ac], XmNleftWidget, fGUI->wWidth); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( label89,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label88); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( fGUI->wWidth,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 8); ac++;
  XtSetArg(al[ac], XmNleftWidget, fGUI->wX); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( label90,al, ac );
  ac = 0;
  XtAddCallback( fGUI->wX, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)X_RC );
  XtAddCallback( fGUI->wY, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)Y_RC );
  XtAddCallback( fGUI->wHeight, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)X_RC );
  XtAddCallback( fGUI->wWidth, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)Y_RC );
  children[ac++] = label87;
  children[ac++] = fGUI->wX;
  children[ac++] = fGUI->wY;
  children[ac++] = label88;
  children[ac++] = fGUI->wHeight;
  children[ac++] = label89;
  children[ac++] = fGUI->wWidth;
  children[ac++] = label90;
  XtManageChildren(children, ac);
  ac = 0;
  XtAddCallback( fGUI->wInPixelTGL, XmNvalueChangedCallback, cbFaceplateCoordinates, (XtPointer) FP_INPIXEL );
  XtAddCallback( fGUI->wFractionBaseTGL, XmNvalueChangedCallback, cbFaceplateCoordinates, (XtPointer) FP_FRACTIONBASE );
  children[ac++] = fGUI->wInPixelTGL;
  children[ac++] = fGUI->wFractionBaseTGL;
  XtManageChildren(children, ac);
  ac = 0;
  XtAddCallback( fGUI->wFractionBaseTXT, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)X_RC);
  children[ac++] = label84;
  children[ac++] = label85;
  children[ac++] = fGUI->wTitle;
  children[ac++] = label86;
  children[ac++] = fGUI->wNotes;
  children[ac++] = form42;
  children[ac++] = form43;
  children[ac++] = label91;
  children[ac++] = radioBox3;
  children[ac++] = label2;
  children[ac++] = fGUI->wFractionBaseTXT;
  XtManageChildren(children, ac);
  ac = 0;
  children[ac++] = form41;
  children[ac++] = label92;
  XtManageChildren(children, ac);
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetValues ( scrolledWin8,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetValues ( fGUI->wGroupRowColumn,al, ac );
  ac = 0;
  children[ac++] = fGUI->wGroupRowColumn;
  XtManageChildren(children, ac);
  ac = 0;
  children[ac++] = fGUI->wGroupForm;
  XtManageChildren(children, ac);
  ac = 0;
  XmScrolledWindowSetAreas(scrolledWin8, scrollbar31, scrollbar32, fGUI->wGroupForm );
  children[ac++] = scrolledWin8;
  XtManageChildren(children, ac);
  ac = 0;
  children[ac++] = form44;
  children[ac++] = label93;
  XtManageChildren(children, ac);
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, frame18); ac++;
  XtSetValues ( label95,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopWidget, label95); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 2); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, frame18); ac++;
  XtSetValues ( rowcol14,al, ac );
  ac = 0;


  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomWidget, separator20); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 2); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( form47,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 4); ac++;
  XtSetArg(al[ac], XmNbottomWidget, separator21); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 0); ac++;
  XtSetValues ( form48,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomWidget, form47); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, frame18); ac++;
  XtSetValues ( label102,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomWidget, form48); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 4); ac++;
  XtSetValues ( frame18,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomWidget, label102); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 2); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, frame18); ac++;
  XtSetValues ( separator19,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 2); ac++;
  XtSetArg(al[ac], XmNbottomWidget, form48); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 2); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightWidget, frame18); ac++;
  XtSetValues ( separator20,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 4); ac++;
  XtSetArg(al[ac], XmNbottomWidget, fGUI->wDeleteFaceplate); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 4); ac++;
  XtSetValues ( separator21,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 4); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 1); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNrightPosition, 3); ac++;
  XtSetValues ( fGUI->wAddNewFaceplate,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 4); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNrightPosition, 6); ac++;
  XtSetValues ( fGUI->wApplayChanges,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 4); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 7); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNrightPosition, 9); ac++;
  XtSetValues ( fGUI->wDeleteFaceplate,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNtopWidget, fGUI->wFaceplateReset); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomWidget, separator19); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightWidget, frame18); ac++;
  XtSetValues ( form51,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopWidget, rowcol14); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNleftPosition, 1); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( fGUI->wFaceplateReset,al, ac );
  ac = 0;
  XtAddCallback( fGUI->wCell00, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_00 );
  XtAddCallback( fGUI->wCell10, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_10 );
  XtAddCallback( fGUI->wCell20, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_20 );
  XtAddCallback( fGUI->wCell30, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_30 );
  XtAddCallback( fGUI->wCell40, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_40 );
  XtAddCallback( fGUI->wCell50, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_50 );
  XtAddCallback( fGUI->wCell60, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_60 );
  XtAddCallback( fGUI->wCell70, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_70 );
  children[ac++] = fGUI->wCell00;
  children[ac++] = fGUI->wCell10;
  children[ac++] = fGUI->wCell20;
  children[ac++] = fGUI->wCell30;
  children[ac++] = fGUI->wCell40;
  children[ac++] = fGUI->wCell50;
  children[ac++] = fGUI->wCell60;
  children[ac++] = fGUI->wCell70;
  XtManageChildren(children, ac);
  ac = 0;
  XtAddCallback( fGUI->wCell01, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_01 );
  XtAddCallback( fGUI->wCell11, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_11 );
  XtAddCallback( fGUI->wCell21, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_21 );
  XtAddCallback( fGUI->wCell31, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_31 );
  XtAddCallback( fGUI->wCell41, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_41 );
  XtAddCallback( fGUI->wCell51, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_51 );
  XtAddCallback( fGUI->wCell61, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_61 );
  XtAddCallback( fGUI->wCell71, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_71 );
  children[ac++] = fGUI->wCell01;
  children[ac++] = fGUI->wCell11;
  children[ac++] = fGUI->wCell21;
  children[ac++] = fGUI->wCell31;
  children[ac++] = fGUI->wCell41;
  children[ac++] = fGUI->wCell51;
  children[ac++] = fGUI->wCell61;
  children[ac++] = fGUI->wCell71;
  XtManageChildren(children, ac);
  ac = 0;
  children[ac++] = rowcol15;
  children[ac++] = rowcol16;
  XtManageChildren(children, ac);
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomWidget, label98); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightOffset, 0); ac++;
  XtSetArg(al[ac], XmNrightWidget, label98); ac++;
  XtSetValues ( label97,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label97); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( fGUI->wFaceplateX,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_POSITION); ac++;
  XtSetArg(al[ac], XmNtopPosition, 50); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( label98,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNtopWidget, fGUI->wFaceplateX); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, fGUI->wFaceplateX); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( fGUI->wFaceplateY,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomWidget, label100); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label100); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightOffset, 0); ac++;
  XtSetArg(al[ac], XmNrightWidget, label100); ac++;
  XtSetValues ( label99,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNtopWidget, fGUI->wFaceplateWidth); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label100); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 0); ac++;
  XtSetValues ( fGUI->wFaceplateHeigth,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNtopWidget, fGUI->wFaceplateX); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNleftWidget, fGUI->wFaceplateY); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( label100,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label99); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 0); ac++;
  XtSetValues ( fGUI->wFaceplateWidth,al, ac );
  ac = 0;
  XtAddCallback( fGUI->wFaceplateX, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)X_RC );
  XtAddCallback( fGUI->wFaceplateY, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)Y_RC );
  XtAddCallback( fGUI->wFaceplateHeigth, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)Y_RC );
  XtAddCallback( fGUI->wFaceplateWidth, XmNmodifyVerifyCallback, textFieldNumericVerifyCallback, (XtPointer)X_RC );
  children[ac++] = label97;
  children[ac++] = fGUI->wFaceplateX;
  children[ac++] = label98;
  children[ac++] = fGUI->wFaceplateY;
  children[ac++] = label99;
  children[ac++] = fGUI->wFaceplateHeigth;
  children[ac++] = label100;
  children[ac++] = fGUI->wFaceplateWidth;
  XtManageChildren(children, ac);
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNbottomOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
  XtSetValues ( label101,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNleftOffset, 0); ac++;
  XtSetArg(al[ac], XmNleftWidget, label101); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNrightOffset, 4); ac++;
  XtSetArg(al[ac], XmNrightWidget, fGUI->wFaceplateAdlFileBrowse); ac++;
  XtSetValues ( fGUI->wSelectedAdlFile,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNtopOffset, 0); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightOffset, 4); ac++;
  XtSetValues ( fGUI->wFaceplateAdlFileBrowse,al, ac );
  ac = 0;
  XtAddCallback( fGUI->wSelectedAdlFile, XmNvalueChangedCallback, cbFaceplateAdlFile, (XtPointer) FP_FACEPLATE_ADL_FILE );
  XtAddCallback( fGUI->wFaceplateAdlFileBrowse, XmNactivateCallback, cbFaceplateAdlFile, (XtPointer) FP_FACEPLATE_ADL_FILE_BROWSE );
  children[ac++] = label101;
  children[ac++] = fGUI->wSelectedAdlFile;
  children[ac++] = fGUI->wFaceplateAdlFileBrowse;
  XtManageChildren(children, ac);
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
  XtSetArg(al[ac], XmNtopOffset, 4); ac++;
  XtSetArg(al[ac], XmNtopWidget, label103); ac++;
  XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetValues ( scrolledWin9,al, ac );
  ac = 0;

  XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
  XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
  XtSetValues ( label103,al, ac );
  ac = 0;
  children[ac++] = fGUI->wFaceplateMacroRowColomn;
  XtManageChildren(children, ac);
  ac = 0;
  XmScrolledWindowSetAreas(scrolledWin9, scrollbar33, scrollbar34, fGUI->wFaceplateMacroRowColomn );
  children[ac++] = scrolledWin9;
  children[ac++] = label103;
  XtManageChildren(children, ac);
  ac = 0;
  children[ac++] = form49;
  children[ac++] = label105;
  XtManageChildren(children, ac);
  ac = 0;
  XtAddCallback( fGUI->wAddNewFaceplate, XmNactivateCallback, cbFaceplateSubmit, (XtPointer) FP_FACEPLATE_ADD_NEW );
  XtAddCallback( fGUI->wApplayChanges, XmNactivateCallback, cbFaceplateSubmit, (XtPointer) FP_FACEPLATE_APPLY );
  XtAddCallback( fGUI->wDeleteFaceplate, XmNactivateCallback, cbFaceplateSubmit, (XtPointer) FP_FACEPLATE_DELETE );
  XtAddCallback( fGUI->wFaceplateReset, XmNactivateCallback, cbFaceplateCell, (XtPointer) FP_FACEPLATE_CELL_RESET);
  children[ac++] = label95;
  children[ac++] = rowcol14;
  children[ac++] = form47;
  children[ac++] = form48;
  children[ac++] = label102;
  children[ac++] = frame18;
  children[ac++] = separator19;
  children[ac++] = separator20;
  children[ac++] = separator21;
  children[ac++] = fGUI->wAddNewFaceplate;
  children[ac++] = fGUI->wApplayChanges;
  children[ac++] = fGUI->wDeleteFaceplate;
  children[ac++] = form51;
  children[ac++] = fGUI->wFaceplateReset;
  XtManageChildren(children, ac);
  ac = 0;
  children[ac++] = label94;
  children[ac++] = form46;
  XtManageChildren(children, ac);
  ac = 0;
  children[ac++] = frame15;
  children[ac++] = frame16;
  children[ac++] = frame17;
  XtManageChildren(children, ac);
  ac = 0;
  children[ac++] = menuBar3;
  children[ac++] = panedWindow1;
  XtManageChildren(children, ac);

  ac = 0;
  children[ac++] = fGUI->wFaceplateDlg;
  XtManageChildren(children, ac);

  ac = 0;
  children[ac++] = fGUI->wFaceplateDlgShell;
  XtManageChildren(children, ac);

  setFaceplateSensitivity(fGUI);
}


void create_adlSelectDlg (Widget parent)
{
  Arg al[64];                    /* Arg List */
  register int ac = 0;           /* Arg Count */
  XmString xmstrings[16];    /* temporary storage for XmStrings */
  Widget fileSelect3 = (Widget)NULL;
  Widget button29 = (Widget)NULL;
  Widget button31 = (Widget)NULL;
  FaceplateGUI * fGUI = getFaceplateGUI(parent);
  char * adlDir =  getenv(DISPLAY_LIST_ENV);


  if (fGUI->wAdlSelectDlg != NULL) {
    XtManageChild(fGUI->wAdlSelectDlg);
    return;
  }

  ac = 0;
  XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
  XtSetArg(al[ac], XmNtitle, "Select Adl File"); ac++;
  fileSelect3 = XmCreateDialogShell ( parent, "wAdlSelectDlg", al, ac );

  ac = 0;
  if (adlDir != NULL) {
    char dirMask[FULLPATHNAME_SIZE+1];

    sprintf(dirMask, "%s%s", adlDir, DISPLAY_DIALOG_MASK);
    xmstrings[0] = XmStringCreateLtoR ( dirMask, (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
    XtSetArg(al[ac], XmNdirMask, xmstrings[0]); ac++;
    xmstrings[1] = XmStringCreateLtoR ( adlDir, (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
    XtSetArg(al[ac], XmNdirSpec, xmstrings[1]); ac++;
    xmstrings[2] = XmStringCreateLtoR ( adlDir, (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
    XtSetArg(al[ac], XmNdirectory, xmstrings[2]); ac++;
    xmstrings[3] = XmStringCreateLtoR ( DISPLAY_DIALOG_MASK, (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
    XtSetArg(al[ac], XmNpattern, xmstrings[3]); ac++;
  }

  fGUI->wAdlSelectDlg = XmCreateFileSelectionBox ( fileSelect3, "fGUI->wAdlSelectDlg", al, ac );
  XtVaSetValues( fGUI->wAdlSelectDlg, 
		 XmNuserData, (XtPointer) DISPLAY_DIALOG_MASK, 
		 NULL );
  fillFileSelBox(fGUI->wAdlSelectDlg);
 
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  XmStringFree ( xmstrings [ 1 ] );
  XmStringFree ( xmstrings [ 2 ] );
  XmStringFree ( xmstrings [ 3 ] );
  button29 = XmSelectionBoxGetChild ( fGUI->wAdlSelectDlg, XmDIALOG_CANCEL_BUTTON );
  XtDestroyWidget(XmSelectionBoxGetChild ( fGUI->wAdlSelectDlg, XmDIALOG_HELP_BUTTON ));
  button31 = XmSelectionBoxGetChild ( fGUI->wAdlSelectDlg, XmDIALOG_OK_BUTTON );
  fGUI->wAdlSelectDlgSelection = XmSelectionBoxGetChild ( fGUI->wAdlSelectDlg, XmDIALOG_TEXT );
  xmstrings[0] = XmStringCreateLtoR ( "Cancel", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetValues ( button29,al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );

  xmstrings[0] = XmStringCreateLtoR ( "OK", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetValues ( button31,al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );

  XtAddCallback(fGUI->wAdlSelectDlg, XmNokCallback, cbAdlFileSelect, (XtPointer)FP_ADL_FILE_SELECT_OK);
  XtAddCallback(fGUI->wAdlSelectDlg,XmNcancelCallback, cbAdlFileSelect, (XtPointer)FP_ADL_FILE_SELECT_CANCEL );

  XtManageChild(fGUI->wAdlSelectDlg);
}


void create_shell2 (Widget parent)
{
  Arg al[64];                    /* Arg List */
  register int ac = 0;           /* Arg Count */
  XmString xmstrings[16];    /* temporary storage for XmStrings */
  Widget button25 = (Widget)NULL;
  Widget button26 = (Widget)NULL;
  Widget button27 = (Widget)NULL;
  FaceplateGUI * fGUI = getFaceplateGUI(parent);

  if (fGUI->wSelectFaceplateDlg != NULL) {
    XtManageChild(fGUI->wSelectFaceplateDlg);
    return;
  }

  XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
  XtSetArg(al[ac], XmNtitle, "Select Faceplace File"); ac++;
  fGUI->wSelectFaceplateShell = XmCreateDialogShell ( parent, "wSelectFaceplateShell", al, ac );
  ac = 0;
  xmstrings[0] = XmStringCreateLtoR ( "*.mfp", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNpattern, xmstrings[0]); ac++;
  fGUI->wSelectFaceplateDlg = XmCreateFileSelectionBox ( fGUI->wSelectFaceplateShell, "wSelectFaceplateDlg", al, ac );
  XtVaSetValues( fGUI->wSelectFaceplateDlg, 
		 XmNuserData, (XtPointer) "*.mfp", 
		 NULL );
  fillFileSelBox(fGUI->wSelectFaceplateDlg);
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );
  button25 = XmSelectionBoxGetChild ( fGUI->wSelectFaceplateDlg, XmDIALOG_CANCEL_BUTTON );
  button26 = XmSelectionBoxGetChild ( fGUI->wSelectFaceplateDlg, XmDIALOG_HELP_BUTTON );
  button27 = XmSelectionBoxGetChild ( fGUI->wSelectFaceplateDlg, XmDIALOG_OK_BUTTON );
  xmstrings[0] = XmStringCreateLtoR ( "Cancel", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetValues ( button25,al, ac );
  XmStringFree ( xmstrings [ 0 ] );

  XtDestroyWidget ( button26);
  ac = 0;

  xmstrings[0] = XmStringCreateLtoR ( "OK", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
  XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
  XtSetValues ( button27,al, ac );
  ac = 0;
  XmStringFree ( xmstrings [ 0 ] );

  XtAddCallback(fGUI->wSelectFaceplateDlg, XmNokCallback, cbFaceplateFileSelect, (XtPointer)FP_FILE_SELECT_OK);
  XtAddCallback(fGUI->wSelectFaceplateDlg, XmNcancelCallback, cbFaceplateFileSelect, (XtPointer)FP_FILE_SELECT_CANCEL);

  XtManageChild(fGUI->wSelectFaceplateDlg);
}

