#
# $Id: Makefile,v 1.7 2009-01-13 10:35:28 birke Exp $
#
TOP = ..
include $(TOP)/configure/CONFIG
DIRS = graphX graphX/printUtils xc libUnix
ifndef XRTHOME
DIRS += jpt
endif
DIRS += dm2k
include $(TOP)/configure/RULES_DIRS
